from typing import Dict, Any, List

class Compiler:
    def __init__(self, policy_data: Dict[str, Any], parser_services: Dict[str, Any]):
        self.policy = policy_data
        self.zones = policy_data.get('zones', {})
        self.rules = policy_data.get('rules', [])
        self.services = {**parser_services, **policy_data.get('services', {})}
        
    def _resolve_ip(self, target: str) -> str:
        """Resolve a zone name or IP address to an actual IP/subnet."""
        if target == 'ANY':
            return '0.0.0.0/0'
        return self.zones.get(target, target)
        
    def _resolve_service(self, svc_name: str) -> Dict[str, Any]:
        """Resolve a service name to port/proto."""
        return self.services.get(svc_name, {'port': svc_name, 'proto': 'tcp'})

    def compile_iptables(self) -> List[str]:
        """Compiles rules to iptables commands."""
        commands = [
            "# Generated by Firewall Policy Compiler",
            "iptables -F",
            "iptables -X",
            "iptables -P INPUT DROP",
            "iptables -P FORWARD DROP",
            "iptables -P OUTPUT ACCEPT",
            "iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
            "iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
            "iptables -A INPUT -i lo -j ACCEPT"
        ]
        
        for rule in self.rules:
            src = self._resolve_ip(rule.get('source', 'ANY'))
            dst = self._resolve_ip(rule.get('destination', 'ANY'))
            action = 'ACCEPT' if str(rule.get('action', '')).upper() == 'ALLOW' else 'DROP'
            
            svcs = rule.get('service', ['ANY'])
            if isinstance(svcs, str):
                svcs = [svcs]
                
            for svc in svcs:
                base_cmd = f"iptables -A FORWARD"
                
                if src != '0.0.0.0/0':
                    base_cmd += f" -s {src}"
                if dst != '0.0.0.0/0':
                    base_cmd += f" -d {dst}"
                    
                if svc != 'ANY':
                    s_details = self._resolve_service(svc)
                    proto = s_details['proto']
                    port = s_details['port']
                    base_cmd += f" -p {proto} --dport {port}"
                
                if rule.get('log'):
                    commands.append(base_cmd + f" -j LOG --log-prefix 'FW_COMPILER_{action}: '")
                    
                base_cmd += f" -j {action}"
                commands.append(base_cmd)
                
        return commands

    def compile_nftables(self) -> str:
        """Compiles rules to nftables syntax."""
        lines = [
            "#!/usr/sbin/nft -f",
            "flush ruleset",
            "table inet filter {",
            "    chain input {",
            "        type filter hook input priority 0; policy drop;",
            "        ct state established,related accept",
            "        iif lo accept",
            "    }",
            "    chain forward {",
            "        type filter hook forward priority 0; policy drop;",
            "        ct state established,related accept"
        ]
        
        for rule in self.rules:
            src = self._resolve_ip(rule.get('source', 'ANY'))
            dst = self._resolve_ip(rule.get('destination', 'ANY'))
            action = 'accept' if str(rule.get('action', '')).upper() == 'ALLOW' else 'drop'
            
            svcs = rule.get('service', ['ANY'])
            if isinstance(svcs, str):
                svcs = [svcs]
                
            for svc in svcs:
                rule_parts = []
                if src != '0.0.0.0/0':
                    rule_parts.append(f"ip saddr {src}")
                if dst != '0.0.0.0/0':
                    rule_parts.append(f"ip daddr {dst}")
                    
                if svc != 'ANY':
                    s_details = self._resolve_service(svc)
                    proto = s_details['proto']
                    port = s_details['port']
                    rule_parts.append(f"{proto} dport {port}")
                    
                if rule.get('log'):
                    log_stmt = f"log prefix \"FW_COMPILER_{action.upper()}: \""
                    lines.append(f"        {' '.join(rule_parts)} {log_stmt}")
                    
                lines.append(f"        {' '.join(rule_parts)} {action}")
                
        lines.append("    }")
        lines.append("    chain output {")
        lines.append("        type filter hook output priority 0; policy accept;")
        lines.append("    }")
        lines.append("}")
        return "\n".join(lines)
